[package]
name = "dislogger"
version = "0.1.0"
authors = ["Matheus Maia <roxx77344@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.7.9"
actix-web = "0.7.18"
actix-net = "0.2.6"
futures = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = "0.1"
log = "0.4"
env_logger = "0.6"
